apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-mysql
  namespace: mysql
spec:
  clusterIP: None
  replicas: 3
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          livenessProbe:
             exec:
               command: ["mysqladmin","ping"]
             initialDelaySeconds: 30
             periodSeconds: 10
             timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysqladmin","ping" ]
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 50m
              memory: 250Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi

